/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef PCMFLOWOPUS_VERSION_H
#define PCMFLOWOPUS_VERSION_H

#define PCMFLOWOPUS_VERSION_MAJOR 0
#define PCMFLOWOPUS_VERSION_MINOR 2
#define PCMFLOWOPUS_VERSION_PATCH 0
#define PCMFLOWOPUS_VERSION_STR "0.2.0"

#endif // PCMFLOWOPUS_VERSION_H
